// Code generated by tygo. DO NOT EDIT.
/**
 * AUTO-GENERATED TypeScript types from Go models
 *
 * DO NOT EDIT THIS FILE DIRECTLY!
 *
 * To regenerate types, run:
 *   make types
 *
 * Source: backend/models/
 */

//////////
// source: banner.go

/**
 * BannerSeverity controls how a Banner is styled in the UI.
 * tygo:export
 */
export type BannerSeverity = string;
export const BannerSeverityInfo: BannerSeverity = 'info';
export const BannerSeverityWarning: BannerSeverity = 'warning';
export const BannerSeverityError: BannerSeverity = 'error';
/**
 * Banner is a transient, server-derived message surfaced in the UI.
 * Banners are computed on demand (see services.BannerService) and never
 * persisted: a banner exists exactly while its underlying condition is true.
 * tygo:export
 */
export interface Banner {
	/**
	 * ID is stable for the lifetime of the underlying condition, so the
	 * frontend can key list rendering and remember per-banner dismissals.
	 */
	id: string;
	/**
	 * Severity controls styling.
	 */
	severity: BannerSeverity;
	/**
	 * Message is the full, display-ready text. The backend authors it so a new
	 * banner needs no frontend change.
	 */
	message: string;
	/**
	 * Dismissible reports whether the user may hide the banner. Dismissal state
	 * is held client-side; the backend stays stateless.
	 */
	dismissible: boolean;
	/**
	 * Link is an optional call to action.
	 */
	link?: BannerLink;
}
/**
 * BannerLink is an optional call-to-action rendered alongside a Banner.
 * tygo:export
 */
export interface BannerLink {
	label: string;
	href: string;
}

//////////
// source: base.go
/*
Package models defines the domain models for ShowMyCards.
These models represent the database schema and are the single source of truth for data structures.
*/

/**
 * BaseModel represents the base model with common fields
 * tygo:export
 */
export interface BaseModel {
	id: number /* uint */;
	created_at: string;
	updated_at: string;
}

//////////
// source: card.go

/**
 * Card represents a Magic card from Scryfall's bulk data
 * Stores the complete card data as JSON to avoid duplication
 * tygo:export
 */
export interface Card {
	scryfall_id: string;
	oracle_id: string; // Can be empty for tokens/emblems
	/**
	 * Generated columns (created via migration, not by GORM)
	 * These are read-only and populated by SQLite from RawJSON
	 * Use "-" tag to exclude from AutoMigrate entirely
	 */
	name: string;
	set_code: string;
}
/**
 * PrintKey identifies a printing by its set code and collector number, which a
 * card shares across all of its language variants.
 */
export interface PrintKey {
	SetCode: string;
	CollectorNumber: string;
}

//////////
// source: deck.go

/**
 * Deck represents a user-defined deck of cards.
 * A deck is a declarative want-list: it does not hold cards directly. Owned
 * copies live in Inventory; "decked" status is derived by the allocation
 * service from the deck's items.
 * tygo:export
 */
export interface Deck {
	BaseModel: BaseModel;
	name: string;
	description?: string;
	/**
	 * Relationship - items in this deck
	 */
	items?: DeckItem[];
}

//////////
// source: deck_item.go

/**
 * DeckZone is where a card sits within a deck.
 * tygo:export
 */
export type DeckZone = string;
export const ZoneMain: DeckZone = 'main';
export const ZoneSide: DeckZone = 'side';
export const ZoneCommand: DeckZone = 'command';
export const ZoneMaybe: DeckZone = 'maybe';
/**
 * DeckItem represents a single card entry in a deck.
 * ScryfallID is empty when the user does not pin a specific printing (any
 * printing of the Oracle satisfies the entry); Treatment is empty when the
 * user does not pin a specific finish. Both are stored as empty strings rather
 * than NULL: SQLite treats NULLs as distinct in a unique index, which would
 * allow duplicate "any printing" rows past the composite uniqueness check.
 * Treatment is carried through but is NOT factored into the global
 * over-commitment math in Milestone 1 (see FR98/IMPLEMENTATION_PLAN.md §2).
 * tygo:export
 */
export interface DeckItem {
	BaseModel: BaseModel;
	deck_id: number /* uint */;
	oracle_id: string;
	scryfall_id: string;
	treatment: string;
	zone: DeckZone;
	desired_quantity: number /* int */;
	/**
	 * Relationship
	 */
	deck?: Deck;
}

//////////
// source: inventory.go

/**
 * Inventory represents a card in the collection
 * tygo:export
 */
export interface Inventory {
	BaseModel: BaseModel;
	scryfall_id: string;
	oracle_id: string;
	treatment: string;
	quantity: number /* int */;
	storage_location_id?: number /* uint */;
	/**
	 * Relationship
	 */
	storage_location?: StorageLocation;
}

//////////
// source: job.go

/**
 * JobType represents the type of job
 * tygo:export
 */
export type JobType = string;
export const JobTypeBulkDataImport: JobType = 'bulk_data_import';
export const JobTypeSetDataImport: JobType = 'set_data_import';
/**
 * JobStatus represents the status of a job
 * tygo:export
 */
export type JobStatus = string;
export const JobStatusPending: JobStatus = 'pending';
export const JobStatusInProgress: JobStatus = 'in_progress';
export const JobStatusCompleted: JobStatus = 'completed';
export const JobStatusFailed: JobStatus = 'failed';
export const JobStatusCancelled: JobStatus = 'cancelled';
/**
 * Job represents a long-running background job
 * tygo:export
 */
export interface Job {
	BaseModel: BaseModel;
	type: JobType;
	status: JobStatus;
	started_at?: string;
	completed_at?: string;
	error?: string;
	metadata?: string; // JSON stored as string
}

//////////
// source: list.go

/**
 * List represents a collection of cards the user wants to acquire
 * tygo:export
 */
export interface List {
	BaseModel: BaseModel;
	name: string;
	description?: string;
	/**
	 * Relationship - items in this list
	 */
	items?: ListItem[];
}

//////////
// source: list_item.go

/**
 * ListItem represents a single card entry in a list
 * tygo:export
 */
export interface ListItem {
	BaseModel: BaseModel;
	list_id: number /* uint */;
	scryfall_id: string;
	oracle_id: string;
	treatment: string;
	desired_quantity: number /* int */;
	collected_quantity: number /* int */;
	/**
	 * Relationship
	 */
	list?: List;
}

//////////
// source: set.go

/**
 * tygo:export
 */
export interface Set {
	scryfall_id: string;
	code: string;
	name: string;
	set_type: string;
	released_at?: string;
	card_count: number /* int */;
	digital: boolean;
	icon_filename: string;
	parent_set_code: string;
}

//////////
// source: setting.go

/**
 * tygo:export
 */
export interface Setting {
	BaseModel: BaseModel;
	key: string;
	value: string;
}

//////////
// source: sorting_rule.go

/**
 * SortingRule represents a rule for automatically sorting cards into storage locations
 * tygo:export
 */
export interface SortingRule {
	BaseModel: BaseModel;
	name: string;
	priority: number /* int */;
	expression: string;
	storage_location_id: number /* uint */;
	enabled: boolean;
	/**
	 * Relationship
	 */
	storage_location?: StorageLocation;
}

//////////
// source: storage.go

/**
 * StorageType represents the type of storage location
 * tygo:export
 */
export type StorageType = string;
export const Box: StorageType = 'Box';
export const Binder: StorageType = 'Binder';
/**
 * tygo:export
 */
export interface StorageLocation {
	BaseModel: BaseModel;
	name: string;
	storage_type: StorageType;
}
